// RoomKey.swift
// SharingInstant
//
// Type-safe room key for schema-driven presence subscriptions.

import Foundation

// MARK: - RoomKey

/// A type-safe key identifying a room type and its presence data shape.
///
/// Room keys are generated by the schema codegen and used with
/// `@Shared(.instantPresence(...))` to create type-safe presence subscriptions.
///
/// ## Example
///
/// ```swift
/// // Generated by schema codegen:
/// extension Schema {
///   enum Rooms {
///     static let chat = RoomKey<ChatPresence>(type: "chat")
///   }
/// }
///
/// // Usage:
/// @Shared(.instantPresence(
///   Schema.Rooms.chat,
///   roomId: "room-123",
///   initialPresence: ChatPresence(name: "Alice")
/// ))
/// var presence: RoomPresence<ChatPresence>
/// ```
public struct RoomKey<Presence: Codable & Sendable & Equatable>: Sendable, Hashable {
  /// The room type identifier (e.g., "chat", "cursors").
  public let type: String
  
  /// Creates a room key for the given room type.
  ///
  /// - Parameter type: The room type identifier.
  public init(type: String) {
    self.type = type
  }
}

// MARK: - TopicKey

/// A type-safe key identifying a topic and its payload data shape.
///
/// Topic keys are generated by the schema codegen and used with
/// `@Shared(.instantTopic(...))` to create type-safe topic subscriptions.
///
/// ## Example
///
/// ```swift
/// // Generated by schema codegen:
/// extension Schema {
///   enum Topics {
///     static let emoji = TopicKey<EmojiTopic>(roomType: "reactions", topic: "emoji")
///   }
/// }
///
/// // Usage:
/// @Shared(.instantTopic(
///   Schema.Topics.emoji,
///   roomId: "room-123"
/// ))
/// var channel: TopicChannel<EmojiTopic>
/// ```
public struct TopicKey<Payload: Codable & Sendable & Equatable>: Sendable, Hashable {
  /// The room type this topic belongs to.
  public let roomType: String
  
  /// The topic name within the room.
  public let topic: String
  
  /// Creates a topic key for the given room type and topic.
  ///
  /// - Parameters:
  ///   - roomType: The room type identifier.
  ///   - topic: The topic name.
  public init(roomType: String, topic: String) {
    self.roomType = roomType
    self.topic = topic
  }
}

