// Rooms.swift
// Generated from instant.schema.ts
//
// This file contains type-safe presence and topic types for InstantDB rooms.
// In production, this would be auto-generated by the InstantSchemaPlugin.

import Foundation
import SharingInstant

// MARK: - Room Presence Types

/// Presence data for 'avatars' room.
public struct AvatarsPresence: Codable, Sendable, Equatable {
  public var name: String
  public var color: String
  
  public init(name: String, color: String) {
    self.name = name
    self.color = color
  }
}

/// Presence data for 'chat' room.
public struct ChatPresence: Codable, Sendable, Equatable {
  public var name: String
  public var color: String
  public var isTyping: Bool
  
  public init(name: String, color: String, isTyping: Bool = false) {
    self.name = name
    self.color = color
    self.isTyping = isTyping
  }
}

/// Presence data for 'cursors' room.
public struct CursorsPresence: Codable, Sendable, Equatable {
  public var name: String
  public var color: String
  public var cursorX: Double
  public var cursorY: Double
  
  public init(name: String, color: String, cursorX: Double = 0, cursorY: Double = 0) {
    self.name = name
    self.color = color
    self.cursorX = cursorX
    self.cursorY = cursorY
  }
}

/// Presence data for 'reactions' room.
public struct ReactionsPresence: Codable, Sendable, Equatable {
  public var name: String
  
  public init(name: String) {
    self.name = name
  }
}

/// Presence data for 'tileGame' room.
public struct TileGamePresence: Codable, Sendable, Equatable {
  public var name: String
  public var color: String
  
  public init(name: String, color: String) {
    self.name = name
    self.color = color
  }
}

// MARK: - Topic Payload Types

/// Topic payload for 'reactions.emoji' events.
public struct EmojiTopic: Codable, Sendable, Equatable {
  public var name: String
  public var directionAngle: Double
  public var rotationAngle: Double
  
  public init(name: String, directionAngle: Double, rotationAngle: Double) {
    self.name = name
    self.directionAngle = directionAngle
    self.rotationAngle = rotationAngle
  }
}

// MARK: - Room Keys

public extension Schema {
  /// Type-safe room keys for presence subscriptions.
  enum Rooms {
    /// 'avatars' room - presence sync
    public static let avatars = RoomKey<AvatarsPresence>(type: "avatars")
    
    /// 'chat' room - presence sync
    public static let chat = RoomKey<ChatPresence>(type: "chat")
    
    /// 'cursors' room - presence sync
    public static let cursors = RoomKey<CursorsPresence>(type: "cursors")
    
    /// 'reactions' room - presence sync
    public static let reactions = RoomKey<ReactionsPresence>(type: "reactions")
    
    /// 'tileGame' room - presence sync
    public static let tileGame = RoomKey<TileGamePresence>(type: "tileGame")
  }
}

// MARK: - Topic Keys

public extension Schema {
  /// Type-safe topic keys for fire-and-forget events.
  enum Topics {
    /// 'emoji' topic in 'reactions' room
    public static let emoji = TopicKey<EmojiTopic>(roomType: "reactions", topic: "emoji")
  }
}

// MARK: - Schema Namespace (for generated rooms)

/// Schema namespace for generated types.
///
/// This would normally be generated alongside entity types.
public enum Schema {}

